name: park_pro
description: PARK-PRO Home Page
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  url_launcher: ^6.1.7
  image_picker: ^1.0.4
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  speech_to_text: ^7.3.0
  uuid: ^4.4.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
